create table if not exists students (
  id bigint generated by default as identity primary key,
  name varchar(100) not null,
  major varchar(100) not null,
  image_url text,
  created_at timestamp with time zone default now()
);

insert into students (name, major, image_url)
values
  ('Stanley', 'Computer Science', null),
  ('Budi', 'Information Systems', null);